import React from 'react';
import { Link } from 'react-router-dom';

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-gray-950">
      <div className="border-b border-gray-800">
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-3">
            <div className="w-10 h-10 bg-gradient-to-br from-indigo-500 to-purple-500 rounded-xl flex items-center justify-center">
              <span className="text-xl">🎭</span>
            </div>
            <span className="text-xl font-bold text-white">Persona Studio</span>
          </Link>
          <Link to="/" className="text-gray-400 hover:text-white transition-colors text-sm">Back to Home</Link>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
          <p className="text-gray-400">Last updated: August 1, 2026</p>
        </div>

        <div className="bg-gray-900 border border-gray-800 rounded-xl p-8 space-y-8">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Introduction</h2>
            <p className="text-gray-300 leading-relaxed">
              Welcome to Persona Studio. We are committed to protecting your personal information and your right to
              privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information
              when you use our AI-powered identity transformation platform.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Information We Collect</h2>
            <div className="text-gray-300 leading-relaxed space-y-4">
              <div>
                <h3 className="text-lg font-medium text-white mb-2">Personal Information</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Name and email address when you create an account</li>
                  <li>Username and password (stored securely using industry-standard hashing)</li>
                  <li>Payment information processed through secure third-party payment processors</li>
                  <li>Profile information you choose to provide</li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white mb-2">Content Data</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>Images and videos you upload for AI processing</li>
                  <li>Audio files for voice cloning features</li>
                  <li>Processed outputs generated by our AI models</li>
                </ul>
              </div>
              <div>
                <h3 className="text-lg font-medium text-white mb-2">Usage Data</h3>
                <ul className="list-disc list-inside space-y-2 ml-4">
                  <li>API usage patterns and transformation history</li>
                  <li>Device information (browser type, operating system, IP address)</li>
                  <li>Interaction data (pages visited, features used, time spent)</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. How We Use Your Information</h2>
            <div className="text-gray-300 leading-relaxed space-y-3">
              <p>We use your information to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Provide, maintain, and improve the Service</li>
                <li>Process your AI transformations and deliver results</li>
                <li>Manage your account, credits, and transactions</li>
                <li>Send you service-related communications and updates</li>
                <li>Respond to your inquiries and provide customer support</li>
                <li>Detect and prevent fraud, abuse, and security issues</li>
                <li>Comply with legal obligations and enforce our terms</li>
                <li>Analyze usage patterns to improve our AI models and user experience</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Content Processing and Storage</h2>
            <div className="text-gray-300 leading-relaxed space-y-3">
              <p>Regarding your uploaded content:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>All uploaded files are encrypted both in transit and at rest</li>
                <li>Files are automatically deleted from our servers within 24 hours of processing</li>
                <li>We do not use your uploaded content to train our AI models without explicit consent</li>
                <li>Processed results are stored temporarily for download and auto-delete after 7 days</li>
                <li>You can request immediate deletion of your data at any time</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Data Sharing and Disclosure</h2>
            <div className="text-gray-300 leading-relaxed space-y-3">
              <p>We may share your information with:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li><strong>Service Providers:</strong> Third-party companies that help us operate the Service (hosting, payment processing, analytics)</li>
                <li><strong>Legal Requirements:</strong> When required by law, court order, or government regulation</li>
                <li><strong>Business Transfers:</strong> In connection with a merger, acquisition, or sale of assets</li>
                <li><strong>With Your Consent:</strong> When you explicitly authorize us to share your information</li>
              </ul>
              <p className="mt-3">We do not sell your personal information to third parties for marketing purposes.</p>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Data Security</h2>
            <p className="text-gray-300 leading-relaxed">
              We implement industry-standard security measures including SSL/TLS encryption, AES-256 encryption at rest,
              secure password hashing (bcrypt), regular security audits, and access controls. However, no method of
              transmission or storage is 100% secure, and we cannot guarantee absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Your Rights</h2>
            <div className="text-gray-300 leading-relaxed space-y-3">
              <p>You have the right to:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Access and download your personal data</li>
                <li>Correct inaccurate or incomplete data</li>
                <li>Request deletion of your personal data</li>
                <li>Object to or restrict processing of your data</li>
                <li>Data portability (receive your data in a structured format)</li>
                <li>Withdraw consent at any time</li>
                <li>Lodge a complaint with a supervisory authority</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Cookies and Tracking</h2>
            <p className="text-gray-300 leading-relaxed">
              We use essential cookies to maintain your session and preferences. We do not use third-party advertising
              cookies or tracking technologies. You can manage cookie preferences through your browser settings. For
              more details, see our{' '}
              <Link to="/cookies" className="text-indigo-400 hover:text-indigo-300">Cookie Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. International Data Transfers</h2>
            <p className="text-gray-300 leading-relaxed">
              Your information may be processed in countries other than your own. We ensure that appropriate safeguards
              are in place for international transfers, including standard contractual clauses where required by
              applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Children's Privacy</h2>
            <p className="text-gray-300 leading-relaxed">
              The Service is not intended for users under the age of 18. We do not knowingly collect personal information
              from children. If we become aware that we have collected data from a child, we will take steps to delete
              it promptly.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Changes to This Policy</h2>
            <p className="text-gray-300 leading-relaxed">
              We may update this Privacy Policy from time to time. We will notify you of significant changes by posting
              the new policy on this page and updating the "Last updated" date. We encourage you to review this policy
              periodically.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Contact Us</h2>
            <p className="text-gray-300 leading-relaxed">
              If you have questions about this Privacy Policy or wish to exercise your data rights, please contact us at{' '}
              <Link to="/contact" className="text-indigo-400 hover:text-indigo-300">privacy@personastudio.ai</Link>{' '}
              or visit our <Link to="/contact" className="text-indigo-400 hover:text-indigo-300">Contact page</Link>.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
